categories:
- destinations
- tips

collections:
 products:
   enabled: true
   output: true

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Space
        icon: block
        value:
          _section-type: space-block
      - label: Hero
        icon: star
        value:
          _section-type: hero
          hero_image:
          heading:
          quote:
          subheading:
          optional-subheading:
      - label: 3 Recent Videos
        icon: video_library
        value:
          _section-type: recent-videos
          heading:
          cute-icon_image:
          cute-icon-image-alt:
      - label: Grid
        icon: view_module
        value:
          _section-type: grid
          first-grid:
            heading:
            icon:
            link:
          second-grid:
            heading:
            icon:
            link:          
          third-grid:
            heading:
            icon:
            link:
      - label: Video Block
        icon: smart_display
        value:
          _section-type: video
          embed-youtube-video:
      - label: Read More Grid
        icon: grid_view 
        value:
          _section-type: read-more-grid
          top:
           image:
           heading:
           textarea:
           cta:
           link:
          bottom:
           image:
           heading:
           textarea:
           cta:
           link:
      - label: Gallery
        icon: photo_camera
        value:
          _section-type: gallery
          heading:
          1_image:
          2_image:
          3_image:
          4_image:
          5_image:
          6_image: 
      - label: Scrapbook
        icon: more
        value: 
          _section-type: scrapbook
          top:
            textarea_html: 
            name:
            image:
          bottom: 
            textarea_html: 
            name:
            image: 
      - label: Signature
        icon: create
        value: 
          _section-type: signature
          signature:
      - label: Page Break
        icon: insert_page_break
        value: 
          _section-type: page-break
          image:
      - label: Basic Text Block
        icon: article
        value: 
          _section-type: basic-text-block
          heading:
          textarea_html: 
      - label: Social Media Icons
        icon: groups
        value: 
         _section-type: social-media-icons
         instagram: 
           link: 
           icon: 
         facebook:
          link:
          icon: 
         youtube:
          link:
          icon:
         tiktok:
          link:
          icon: 
         heading:
      - label: Text Block with Icon 
        icon: insert_emoticon
        value: 
         _section-type: text-with-icon
         top: 
          icon: 
          textarea_html:
         bottom:
          icon:
          textarea_html:  
      - label: Sign Up
        icon: list
        value:
         _section-type: sign-up
         heading:

           
