categories:
- destinations
- tips

products:
   enabled: true
   output: true

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Space
        icon: block
        value:
          _section-type: space-block
      - label: Hero
        icon: star
        value:
          _section-type: hero
          hero_image:
          hero-textarea_html:
          cta:
          cta-link:
      - label: 3 Recent Videos
        icon: video_library
        value:
          _section-type: recent-videos
          heading:
          cute-icon_image:
          cute-icon-image-alt:
      - label: Grid
        icon: view_module
        value:
          _section-type: grid
          first-grid:
            heading:
            icon:
            link:
          second-grid:
            heading:
            icon:
            link:          
          third-grid:
            heading:
            icon:
            link:
      - label: Video Block
        icon: smart_display
        value:
          _section-type: video
          embed-youtube-video:
      - label: Text Grid
        icon: grid_view 
        value:
          _section-type: text-grid
          top:
           image:
           heading:
           textarea:
           cta:
           link:
          bottom:
           image:
           heading:
           textarea:
           cta:
           link:
      - label: Gallery
        icon: photo_camera
        value:
          _section-type: gallery
          heading:
          1_image:
          2_image:
          3_image:
          4_image:
          5_image:
          6_image: 
