defaults:
  -
    scope:
      path: "/products"
      type: "pages"
    values:
      layout: "products"
  -
    scope:
      path: "affiliates"
      type: "pages" 
    values:
      layout: "affiliates" # overrides previous default layout

categories:
- destinations
- tips

collections:
 products:
   enabled: true
   output: true
   icon: shopping_cart
 affiliates:
   enabled: true
   output: true
   icon: monetization_on

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Space
        icon: block
        value:
          _section-type: space-block
      - label: Hero
        icon: star
        value:
          _section-type: hero
          hero_image:
          heading:
          quote:
          subheading:
          optional-subheading:
      - label: 3 Recent Videos
        icon: video_library
        value:
          _section-type: recent-videos
          heading:
          cute-icon_image:
          cute-icon-image-alt:
      - label: Grid
        icon: view_module
        value:
          _section-type: grid
          first-grid:
            heading:
            icon:
            link:
          second-grid:
            heading:
            icon:
            link:          
          third-grid:
            heading:
            icon:
            link:
      - label: Video Hero
        icon: smart_display
        value:
          _section-type: video-hero
          heading: 
          subheading: 
          video-path: 
          poster-image:
      - label: Read More Grid
        icon: grid_view 
        value:
          _section-type: read-more-grid
          top:
           image:
           heading:
           textarea:
           cta:
           link:
          bottom:
           image:
           heading:
           textarea:
           cta:
           link:
      - label: Gallery
        icon: photo_camera
        value:
          _section-type: gallery
          heading:
          1_image:
          2_image:
          3_image:
          4_image:
          5_image:
          6_image: 
      - label: Scrapbook
        icon: more
        value: 
          _section-type: scrapbook
          top:
            textarea_html: 
            name:
            image:
          bottom: 
            textarea_html: 
            name:
            image: 
      - label: Signature
        icon: create
        value: 
          _section-type: signature
          signature:
      - label: Page Break
        icon: insert_page_break
        value: 
          _section-type: page-break
          image:
      - label: Basic Text Block
        icon: article
        value: 
          _section-type: basic-text-block
          heading:
          textarea_html:
      - label: Script
        icon: forum
        value:
          _section-type: script
          insert-script-here: 
      - label: Basic Sign Up
        icon: contact_mail
        value: 
         _section-type: basic-sign-up
         form-heading:
         form-text-area:
      - label: Text Block with Icon 
        icon: rtt
        value: 
         _section-type: text-with-icon
         top:
          textarea_html: 
          icon: 
         bottom:
          textarea_html:  
          icon:
      - label: Fun Sign Up
        icon: draw
        value:
         _section-type: fun-sign-up
         heading:
         image:
         form-heading:
         form-text-area:
      - label: Form
        icon: email
        value:
          _section-type: form
          heading:
          image:
          input-1:
          input-2:
          input-3:
          textarea_html: 
      - label: Youtube Library
        icon: code
        value: 
          _section-type: youtube-library
          embed-youtube-video-here:


           
